name: Automatic_Version 2

on:
  pull_request:
    types:
      - closed

jobs:
  version:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '14'

      - name: Install Dependencies
        run: npm install

      - name: Configure Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Determine Version
        id: determine_version
        run: |
          base_branch=$(jq -r .pull_request.base.ref $GITHUB_EVENT_PATH)
          branch_name=$(jq -r .pull_request.head.ref $GITHUB_EVENT_PATH)

          if [[ $branch_name == 'dev' ]]; then
            if [[ $branch_name == *feat/* ]]; then
              if [[ ${{ github.event.action }} == 'closed' && ${{ github.event.pull_request.merged }} == 'true' ]]; then
                npm version prerelease --preid=alpha
              fi
            elif [[ $branch_name == *reintegrate/* ]]; then
              if [[ ${{ github.event.action }} == 'closed' && ${{ github.event.pull_request.merged }} == 'true' ]]; then
                new_version=$(npm --no-git-tag-version version minor)
                new_version="${new_version}-alpha.0"
              fi
            fi
          elif [[ $branch_name == 'qa' ]]; then
            if [[ $branch_name == 'dev' ]]; then
              if [[ ${{ github.event.action }} == 'closed' && ${{ github.event.pull_request.merged }} == 'true' ]]; then
                npm version prerelease --preid=beta
              fi
            elif [[ $branch_name == *fix/* ]]; then
              if [[ ${{ github.event.action }} == 'closed' && ${{ github.event.pull_request.merged }} == 'true' ]]; then
                npm version patch
              fi
            fi
          elif [[ $branch_name == 'main' ]]; then
            if [[ $branch_name == 'qa' ]]; then
              if [[ ${{ github.event.action }} == 'closed' && ${{ github.event.pull_request.merged }} == 'true' ]]; then
                npm version minor
              fi
            elif [[ $branch_name == *fix/* ]]; then
              if [[ ${{ github.event.action }} == 'closed' && ${{ github.event.pull_request.merged }} == 'true' ]]; then
                npm version patch
              fi
            fi
          fi

          echo "::set-output name=base_branch::$base_branch"
          echo "::set-output name=branch_name::$branch_name"

      - name: Get New Version
        id: get_version
        run: echo "::set-output name=version::$(npm version)"

      - name: Commit and Push Version Update
        run: |
          base_branch=${{ steps.determine_version.outputs.base_branch }}
          branch_name=${{ steps.determine_version.outputs.branch_name }}

          echo "Base branch: $base_branch"
          echo "Branch name: $branch_name"

          git fetch origin $base_branch:$base_branch || true
          git checkout $base_branch || true

          git add .
          git commit -am "Update version" || true
          git checkout $base_branch
          git push origin $base_branch --follow-tags || true
